### ISSUE TITLE
only works at beggining of text

### ISSUE THREAD

**Issue by exomarty** [bdharrington7/nodebb-plugin-giphy#1]
Plugin works perfect but it only works at beggining of the text
would be nice to make it work anytime just like mentions or emojis

thanks for the good work

**Comment by bdharrington7** [comment]
Hey, @exomarty, I haven't forgotten about this, I'll push a fix soon

**Comment by bdharrington7** [comment]
closed in 97221a82d0cd5948cdf876af182ad8bb312a3c83
